/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafeteria;

import cafeteria.email;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.sql.Timestamp;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JTable;
import javax.swing.JTextArea;




/**
 *
 * @author HP
 */
public class orders extends javax.swing.JFrame {
    
    public JTable getTable() {
    return jTable1;
}

public JPanel getMainPanel() {
    return jPanel1;
}

    public orders(DefaultTableModel model) {
    initComponents();
    jTable1.setModel(model);
}
    
    private void loadInventoryItems() {
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
        PreparedStatement pst = con.prepareStatement("SELECT item_name, quantity_available, unit_price FROM food_inventory");
        ResultSet rs = pst.executeQuery();

        jComboBox4.removeAllItems();
        HashMap<String, Integer> quantityMap = new HashMap<>();
        HashMap<String, Double> priceMap = new HashMap<>();

        while (rs.next()) {
            String itemName = rs.getString("item_name");
            int quantity = rs.getInt("quantity_available");
            double price = rs.getDouble("unit_price");

            jComboBox4.addItem(itemName);
            quantityMap.put(itemName, quantity);
            priceMap.put(itemName, price);
        }

        // Add listener for item selection
        jComboBox4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String selectedItem = (String) jComboBox4.getSelectedItem();
                if (selectedItem != null) {
                    int availableQty = quantityMap.get(selectedItem);
                    double unitPrice = priceMap.get(selectedItem);

                    // Populate quantity options (1 to availableQty)
                    jComboBox5.removeAllItems();
                    for (int i = 1; i <= availableQty; i++) {
                        jComboBox5.addItem(String.valueOf(i));
                    }

                    // Display unit price
                    jComboBox6.removeAllItems();
                    jComboBox6.addItem("₦" + unitPrice);
                    
                    
                }
            }
        });

        con.close();
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error loading inventory: " + ex.getMessage());
    }
}

List<OrderItem> orderItems = new ArrayList<>();

private void printReceipt(String receiptText) {
        JTextArea textArea = new JTextArea(receiptText);
        try {
            boolean complete = textArea.print();
            if (complete) {
                JOptionPane.showMessageDialog(null, "Receipt sent to printer.");
            } else {
                JOptionPane.showMessageDialog(null, "Printing was cancelled.");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Failed to print receipt: " + ex.getMessage());
        }
    }

public void setReadOnlyMode(boolean readOnly) {
    jButton1.setEnabled(!readOnly); // Place order button
    jButton3.setEnabled(!readOnly); 
    jButton4.setEnabled(!readOnly);
    jButton5.setEnabled(!readOnly);
    jButton6.setEnabled(!readOnly);
    jButton7.setEnabled(!readOnly);
    jButton8.setEnabled(!readOnly);
    jButton10.setEnabled(!readOnly);
    jButton11.setEnabled(!readOnly);
    jButton13.setEnabled(!readOnly);
    jButton14.setEnabled(!readOnly);
    jTextField1.setEditable(!readOnly);
    jTextField5.setEditable(!readOnly);
    jComboBox1.setEnabled(!readOnly);
    jComboBox2.setEnabled(!readOnly);
    jComboBox3.setEnabled(!readOnly);
    jComboBox4.setEnabled(!readOnly);
    jComboBox5.setEnabled(!readOnly);
    jComboBox6.setEnabled(!readOnly);
    jDateChooser1.setEnabled(!readOnly);
    // Add more components as needed
}


    // Expose main panel for dashboard use (assuming jPanel1 is autogenerated by NetBeans)
 public orders() {
         initComponents();
        loadInventoryItems();
        jPanel1.setPreferredSize(new Dimension(1200, 4000));
        jPanel1.setLayout(new BorderLayout());
        
        Timer timer = new Timer(300000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                refreshOrderTable();
            }
        });
        timer.start(); // Start the timer
       
    }

     public void refreshOrderTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // Replace jTable1 with your actual table name
        model.setRowCount(0); // Clear existing rows

        try {
            Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/cafeteria",
                "root",
                "Awele2006"
            );

            String sql = "SELECT * FROM customer_order"; // Replace with your actual table/query
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] row = {
                    rs.getString("order_id"),
                    rs.getString("customer_name"),
                    rs.getString("product_name"),
                    rs.getInt("quantity"),
                    rs.getDouble("unit_price"),
                    rs.getDouble("total_price"),
                    rs.getString("payment_method"),
                    rs.getString("order_status")
                };
                model.addRow(row);
            }

            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Method to load food items into jComboBox4
    private void loadFoodItems() {
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
             Statement st = con.createStatement()) {

            ResultSet rs = st.executeQuery("SELECT item_name FROM food_inventory WHERE quantity_available > 0");
            jComboBox4.removeAllItems();
            while (rs.next()) {
                jComboBox4.addItem(rs.getString("item_name"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading food items: " + e.getMessage());
        }
    }

    // Method to load quantity based on selected item
    private void loadQuantityForSelectedItem() {
        jComboBox5.removeAllItems();

        Object selected = jComboBox4.getSelectedItem();
        if (selected == null) return;

        String item_name = selected.toString();

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006")) {
            String query = "SELECT quantity_available FROM food_inventory WHERE item_name = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, item_name);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                int quantity_available = rs.getInt("quantity_available");

                // Allow selection from 1 to available quantity
                for (int i = 1; i <= quantity_available; i++) {
                    jComboBox5.addItem(String.valueOf(i));
                }
            }

            rs.close();
            pst.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error loading quantity: " + ex.getMessage());
        }
    }

    // Method to load unit price for selected item
    private void loadUnitPriceForSelectedItem() {
        jComboBox6.removeAllItems();

        Object selected = jComboBox4.getSelectedItem();
        if (selected == null) return;

        String item_name = selected.toString();

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006")) {
            String query = "SELECT unit_price FROM food_inventory WHERE item_name = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, item_name);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                double unitPrice = rs.getDouble("unit_price");
                jComboBox6.addItem(String.valueOf(unitPrice));
            }

            rs.close();
            pst.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error loading unit price: " + ex.getMessage());
        }
    }

    // Example: Add action listener to jComboBox4 to update quantity and price when selection changes
    private void setupComboBoxListeners() {
        jComboBox4.addActionListener(e -> {
            loadQuantityForSelectedItem();
            loadUnitPriceForSelectedItem();
        });
    }

    // You can call this in your constructor after loadFoodItems()
    // setupComboBoxListeners();

    // --- Your alertLowInventory() method stays here ---
    public void alertLowInventory() {
        int threshold = 5; // low stock threshold

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
             Statement stmt = con.createStatement()) {

            ResultSet rs = stmt.executeQuery("SELECT item_name, quantity_available FROM food_inventory");

            StringBuilder lowItems = new StringBuilder();
            boolean lowStockFound = false;

            while (rs.next()) {
                int qty = rs.getInt("quantity_available");
                String product = rs.getString("item_name");

                if (qty <= threshold) {
                    lowStockFound = true;
                    lowItems.append(product).append(": ").append(qty).append(" units left\n");
                }
            }

            if (lowStockFound) {
                JOptionPane.showMessageDialog(null,
                        "⚠️ Low Stock Alert:\n" + lowItems.toString(),
                        "Low Stock Warning",
                        JOptionPane.WARNING_MESSAGE);

                String sqlUsers = "SELECT email FROM registration WHERE role IN ('Kitchen', 'Head of Unit')";
                try (PreparedStatement psUsers = con.prepareStatement(sqlUsers);
                     ResultSet rsUsers = psUsers.executeQuery()) {

                    String subject = "⚠️ Low Food Inventory Alert";
                    String messageBody = "<h3>Attention:</h3><p>The following food items are low in inventory:</p><pre>"
                            + lowItems.toString() + "</pre>";

                    while (rsUsers.next()) {
                        String userEmail = rsUsers.getString("email");
                        // You need to define your email sending method somewhere.
                        email.sendEmail(userEmail, subject, messageBody);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
             Statement st = con.createStatement()) {

            ResultSet rs = st.executeQuery("SELECT item_name FROM food_inventory WHERE quantity_available > 0");
            jComboBox4.removeAllItems();
            while (rs.next()) {
                jComboBox4.addItem(rs.getString("item_name"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading food items: " + e.getMessage());
        }
        
    jComboBox5.removeAllItems(); // Clear quantity items

    Object selected = jComboBox4.getSelectedItem();
    if (selected == null) return;

    String item_name = selected.toString();

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
        String query = "SELECT quantity_available FROM food_inventory WHERE item_name = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, item_name);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            int quantity_available = rs.getInt("quantity");
      // Allow selection from 1 to available quantity
      
        }

        rs.close();
        pst.close();
        con.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error loading quantity: " + ex.getMessage());
    }

    jComboBox6.removeAllItems(); // Clear unit price items

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
        String query = "SELECT unit_price FROM food_inventory WHERE item_name = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, item_name);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            double unitPrice = rs.getDouble("unit_price");
            jComboBox6.addItem(String.valueOf(unitPrice));
        }

        rs.close();
        pst.close();
        con.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error loading unit price: " + ex.getMessage());
    }
    }

    // Other methods and event handlers...



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 800));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\cafeteria\\src\\images\\pau_icon-150x150.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        jLabel2.setText("TICKETING STAFF ORDER SYSTEM");

        jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel3.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel4.setText("Product Name");

        jTable1.setBackground(new java.awt.Color(51, 153, 255));
        jTable1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "customer_name", "product_name", "quantity", "unit_price", "total_price", "payment_method", "payment_confirmed", "order_status", "order_time", "order_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton1.setText("Submit Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton3.setText("Add to Table");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton4.setText("Delete from Table");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton5.setText("Delete from Database");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton6.setText("Insert into Database");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel5.setText("Quantity");

        jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel6.setText("Unit Price");

        jLabel7.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel7.setText("Total Price");

        jLabel8.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel8.setText("Payment method");

        jLabel9.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel9.setText("Payment confirmation");

        jLabel10.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel10.setText("Order Status");

        jTextField1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel11.setText("Order Time");

        jComboBox1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Payent method", "cash", "POS", "Transfer", "QR code" }));

        jButton7.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton7.setText("Get from Database");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton8.setText("Update to Database");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item Confirmed?", "Yes", "No" }));

        jComboBox3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order status?", "Completed", "Served", "Not Served" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton10.setText("order confrimation");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton11.setText("Add Item");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton13.setText("Send order ");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton14.setText("Order Preview");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton9.setText("Print Receipt");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(49, 49, 49)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(37, 37, 37))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton14)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(37, 37, 37)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton11)
                                            .addGap(29, 29, 29)
                                            .addComponent(jButton1)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton13)))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(51, 51, 51)
                                .addComponent(jButton4)
                                .addGap(41, 41, 41)
                                .addComponent(jButton9)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton7)
                                    .addComponent(jButton5)
                                    .addComponent(jButton8)
                                    .addComponent(jButton6)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(193, 193, 193))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton14)
                                .addComponent(jButton11)
                                .addComponent(jButton1))
                            .addComponent(jButton13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4)
                                    .addComponent(jButton9)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)
                                .addGap(31, 31, 31)
                                .addComponent(jButton10)))
                        .addGap(199, 265, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    class OrderItem {
    String productName;
    int quantity;
    double unitPrice;

    public OrderItem(String productName, int quantity, double unitPrice) {
        this.productName = productName;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }
    public double getTotal() {
        return quantity * unitPrice;
    }
}
    class Order {
    String customerName;
    String productName;
    int quantity;
    double unitPrice;

    public Order(String customerName, String productName, int quantity, double unitPrice) {
        this.customerName = customerName;
        this.productName = productName;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }

    public double getTotal() {
        return quantity * unitPrice;
    }
}

    


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Connection con = null;
    try {
        String customerName = jTextField1.getText().trim();
        String paymentMethod = jComboBox1.getSelectedItem().toString();
        String paymentConfirmed = jComboBox2.getSelectedItem().toString();
        String orderStatus = jComboBox3.getSelectedItem().toString();

        if (customerName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Customer name is required.");
            return;
        }

        if (!paymentConfirmed.equalsIgnoreCase("Yes")) {
            JOptionPane.showMessageDialog(this, "Payment must be confirmed.");
            return;
        }

        if (orderItems.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No items added to the order.");
            return;
        }

        StringBuilder productNamesStr = new StringBuilder();
        StringBuilder quantitiesStr = new StringBuilder();
        StringBuilder unitPricesStr = new StringBuilder();
        double totalOrderPrice = 0;

        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
        con.setAutoCommit(false);

        for (OrderItem item : orderItems) {
            try (PreparedStatement tempStmt = con.prepareStatement("SELECT quantity_available FROM food_inventory WHERE item_name = ?")) {
                tempStmt.setString(1, item.productName);
                ResultSet rs = tempStmt.executeQuery();
                if (rs.next()) {
                    int availableQty = rs.getInt("quantity_available");
                    if (item.quantity > availableQty) {
                        JOptionPane.showMessageDialog(this, "Only " + availableQty + " units available for " + item.productName);
                        return;
                    }
                }
            }

            productNamesStr.append(item.productName).append(", ");
            quantitiesStr.append(item.quantity).append(", ");
            unitPricesStr.append(item.unitPrice).append(", ");
            totalOrderPrice += item.unitPrice * item.quantity;
        }

        String productName = productNamesStr.toString().replaceAll(", $", "");
        String quantity = quantitiesStr.toString().replaceAll(", $", "");
        String unitPrice = unitPricesStr.toString().replaceAll(", $", "");

        int confirm = JOptionPane.showConfirmDialog(this,
                "Submit order with " + orderItems.size() + " items?\nTotal: ₦" + totalOrderPrice,
                "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        // Generate unique order ID
        String orderId;
        do {
            orderId = "ORD" + UUID.randomUUID().toString().replace("-", "").substring(0, 12).toUpperCase();
            PreparedStatement ps = con.prepareStatement("SELECT COUNT(*) FROM customer_orders WHERE order_id = ?");
            ps.setString(1, orderId);
            ResultSet rs = ps.executeQuery();
            rs.next();
            if (rs.getInt(1) == 0) break;
        } while (true);

        Timestamp orderTime = new Timestamp(System.currentTimeMillis());

        // Insert into customer_orders
        String sql = "INSERT INTO customer_orders (customer_name, product_name, quantity, unit_price, total_price, payment_method, payment_confirmed, order_status, order_time, order_id) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, customerName);
            pst.setString(2, productName);
            pst.setString(3, quantity);
            pst.setString(4, unitPrice);
            pst.setDouble(5, totalOrderPrice);
            pst.setString(6, paymentMethod);
            pst.setString(7, paymentConfirmed);
            pst.setString(8, orderStatus);
            pst.setTimestamp(9, orderTime);
            pst.setString(10, orderId);
            pst.executeUpdate();
        }

        for (OrderItem item : orderItems) {
            try (PreparedStatement updatePst = con.prepareStatement(
                    "UPDATE food_inventory SET quantity_available = quantity_available - ? WHERE item_name = ?")) {
                updatePst.setInt(1, item.quantity);
                updatePst.setString(2, item.productName);
                updatePst.executeUpdate();
            }
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{
                customerName,
                productName,
                quantity,
                unitPrice,
                totalOrderPrice,
                paymentMethod,
                paymentConfirmed,
                orderStatus,
                orderTime,
                orderId
        });

        con.commit();

        JOptionPane.showMessageDialog(this, "Order submitted successfully!\nOrder ID: " + orderId);
        orderItems.clear();
        
        alertLowInventory();

        // Reset UI
        jTextField1.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        jComboBox6.setSelectedIndex(0);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        try {
            if (con != null && !con.isClosed()) {
                con.rollback();
            }
        } catch (Exception rollbackEx) {
            JOptionPane.showMessageDialog(this, "Rollback error: " + rollbackEx.getMessage());
        }
    } finally {
        try {
            if (con != null && !con.isClosed()) {
                con.close();
            }
        } catch (SQLException closeEx) {
            JOptionPane.showMessageDialog(this, "Connection close error: " + closeEx.getMessage());
        }
    }


//        try {
//        String customerName = jTextField1.getText().trim();
//        String paymentMethod = jComboBox1.getSelectedItem().toString();
//        String paymentConfirmed = jComboBox2.getSelectedItem().toString();
//        String orderStatus = jComboBox3.getSelectedItem().toString();
//
//        if (customerName.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Customer name is required.");
//            return;
//        }
//
//        if (!paymentConfirmed.equalsIgnoreCase("Yes")) {
//            JOptionPane.showMessageDialog(this, "Payment must be confirmed.");
//            return;
//        }
//
//        if (orderItems.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "No items added to the order.");
//            return;
//        }
//
//        // Build concatenated strings for products, quantities, unit prices
//        StringBuilder productNames = new StringBuilder();
//        StringBuilder quantities = new StringBuilder();
//        StringBuilder unitPrices = new StringBuilder();
//        double totalOrderPrice = 0;
//
//        for (OrderItem item : orderItems) {
//            // Check inventory for each product (optional but recommended)
//            try (Connection tempCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
//                 PreparedStatement tempStmt = tempCon.prepareStatement("SELECT quantity_available FROM food_inventory WHERE item_name = ?")) {
//                tempStmt.setString(1, item.productName);
//                ResultSet rs = tempStmt.executeQuery();
//                int availableQty = 0;
//                if (rs.next()) {
//                    availableQty = rs.getInt("quantity_available");
//                }
//                if (item.quantity > availableQty) {
//                    JOptionPane.showMessageDialog(this, "Only " + availableQty + " units available for " + item.productName);
//                    return;
//                }
//            }
//
//            if (productNames.length() > 0) {
//                productNames.append(", ");
//                quantities.append(", ");
//                unitPrices.append(", ");
//            }
//            productNames.append(item.productName);
//            quantities.append(item.quantity);
//            unitPrices.append(item.unitPrice);
//            totalOrderPrice += item.unitPrice * item.quantity;
//        }
//
//        // Confirm final submission
//        int finalConfirm = JOptionPane.showConfirmDialog(this, "Submit the order with " + orderItems.size() + " item(s)? Total: " + totalOrderPrice, "Submit Order", JOptionPane.YES_NO_OPTION);
//        if (finalConfirm != JOptionPane.YES_OPTION) {
//            JOptionPane.showMessageDialog(this, "Order cancelled.");
//            return;
//        }
//
//        boolean orderSuccess = false;
//        int maxAttempts = 5;
//        int attempt = 0;
//
//        while (!orderSuccess && attempt < maxAttempts) {
//            attempt++;
//
//            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006")) {
//                con.setAutoCommit(false); // Start transaction
//
//                // Generate unique orderId once per order
//                String orderId = "";
//                boolean unique = false;
//
//                while (!unique) {
//                    orderId = "ORD" + UUID.randomUUID().toString().replace("-", "").substring(0, 12).toUpperCase();
//                    try (PreparedStatement checkIdStmt = con.prepareStatement("SELECT COUNT(*) FROM customer_orders WHERE order_id = ?")) {
//                        checkIdStmt.setString(1, orderId);
//                        ResultSet idRs = checkIdStmt.executeQuery();
//                        if (idRs.next() && idRs.getInt(1) == 0) {
//                            unique = true;
//                        }
//                    }
//                }
//
//                Timestamp orderTime = new Timestamp(System.currentTimeMillis());
//
//                // Insert ONE row with all product info concatenated
//                String sql = "INSERT INTO customer_orders (customer_name, product_names, quantities, unit_prices, total_price, payment_method, payment_confirmed, order_status, order_time, order_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
//                try (PreparedStatement pst = con.prepareStatement(sql)) {
//                    pst.setString(1, customerName);
//                    pst.setString(2, productNames.toString());
//                    pst.setString(3, quantities.toString());
//                    pst.setString(4, unitPrices.toString());
//                    pst.setDouble(5, totalOrderPrice);
//                    pst.setString(6, paymentMethod);
//                    pst.setString(7, paymentConfirmed);
//                    pst.setString(8, orderStatus);
//                    pst.setTimestamp(9, orderTime);
//                    pst.setString(10, orderId);
//                    pst.executeUpdate();
//                }
//
//                // Update inventory quantities for each item
//                for (OrderItem item : orderItems) {
//                    try (PreparedStatement updatePst = con.prepareStatement(
//                            "UPDATE food_inventory SET quantity_available = quantity_available - ? WHERE item_name = ?")) {
//                        updatePst.setInt(1, item.quantity);
//                        updatePst.setString(2, item.productName);
//                        updatePst.executeUpdate();
//                    }
//                }
//
//                // Add to JTable - one row with concatenated products and quantities
//                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//                model.addRow(new Object[]{
//                        customerName,
//                        productNames.toString(),
//                        quantities.toString(),
//                        unitPrices.toString(),
//                        totalOrderPrice,
//                        paymentMethod,
//                        paymentConfirmed,
//                        orderStatus,
//                        orderTime,
//                        orderId
//                });
//
//                con.commit(); // Commit transaction
//                orderItems.clear();
//
//                JOptionPane.showMessageDialog(this, "Order submitted!\nOrder ID: " + orderId);
//
//                // Reset form fields
//                jTextField1.setText("");
//                jComboBox4.setSelectedIndex(0);
//                jComboBox5.setSelectedIndex(0);
//                jComboBox6.setSelectedIndex(0);
//                jComboBox1.setSelectedIndex(0);
//                jComboBox2.setSelectedIndex(0);
//                jComboBox3.setSelectedIndex(0);
//
//                orderSuccess = true;
//            } catch (SQLIntegrityConstraintViolationException dupEx) {
//                // Duplicate orderId found, retry with a new orderId
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(this, "Error processing order: " + e.getMessage());
//                break;
//            }
//        }
//
//        if (!orderSuccess) {
//            JOptionPane.showMessageDialog(this, "Failed to generate unique order ID after multiple attempts. Please try again.");
//        }
//
//    } catch (Exception e) {
//        e.printStackTrace();
//        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
//    }







        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 try {
    String customerName = jTextField1.getText().trim();
    String paymentMethod = jComboBox1.getSelectedItem().toString();
    String paymentConfirmed = jComboBox2.getSelectedItem().toString();
    String orderStatus = jComboBox3.getSelectedItem().toString();

    if (customerName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Customer name is required.");
        return;
    }

    if (orderItems.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No items added to the order.");
        return;
    }

    StringBuilder productNamesStr = new StringBuilder();
    StringBuilder quantitiesStr = new StringBuilder();
    StringBuilder unitPricesStr = new StringBuilder();
    double totalOrderPrice = 0;

    for (OrderItem item : orderItems) {
        productNamesStr.append(item.productName).append(", ");
        quantitiesStr.append(item.quantity).append(", ");
        unitPricesStr.append(item.unitPrice).append(", ");
        totalOrderPrice += item.unitPrice * item.quantity;
    }

    String productName = productNamesStr.toString().replaceAll(", $", "");
    String quantity = quantitiesStr.toString().replaceAll(", $", "");
    String unitPrice = unitPricesStr.toString().replaceAll(", $", "");

    int confirm = JOptionPane.showConfirmDialog(this,
            "Add order with " + orderItems.size() + " items?\nTotal: ₦" + totalOrderPrice,
            "Confirm", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) return;

    Timestamp orderTime = new Timestamp(System.currentTimeMillis());

    // Add to JTable regardless of payment confirmation
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{
            customerName,
            productName,
            quantity,
            unitPrice,
            totalOrderPrice,
            paymentMethod,
            paymentConfirmed,
            orderStatus,
            orderTime
    });

    JOptionPane.showMessageDialog(this, "Order added to table successfully!");
    orderItems.clear();

    // Reset UI
    jTextField1.setText("");
    jComboBox1.setSelectedIndex(0);
    jComboBox2.setSelectedIndex(0);
    jComboBox3.setSelectedIndex(0);
    jComboBox4.setSelectedIndex(0);
    jComboBox5.setSelectedIndex(0);
    jComboBox6.setSelectedIndex(0);

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}



    
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
Connection con = null;
PreparedStatement pstInsert = null;

try {
    // Step 1: Establish DB connection (update URL, user, and password as needed)
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
    con.setAutoCommit(false); // Begin transaction

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    int rowCount = model.getRowCount();
    int insertedCount = 0;
    int skippedCount = 0;

    for (int i = 0; i < rowCount; i++) {
        String paymentConfirmed = model.getValueAt(i, 6).toString().trim();
        if (!paymentConfirmed.equalsIgnoreCase("Yes")) {
            System.out.println("Skipping row " + (i + 1) + " due to unconfirmed payment.");
            continue;
        }

        String customerName = model.getValueAt(i, 0).toString().trim();
        String productName = model.getValueAt(i, 1).toString().trim();
        String quantityStr = model.getValueAt(i, 2).toString().trim();
        String unitPriceStr = model.getValueAt(i, 3).toString().trim();
        String totalPriceStr = model.getValueAt(i, 4).toString().trim();
        String paymentMethod = model.getValueAt(i, 5).toString().trim();
        String orderStatus = model.getValueAt(i, 7).toString().trim();

        // Check for duplicate
        try (PreparedStatement psExist = con.prepareStatement(
                "SELECT COUNT(*) FROM customer_orders WHERE customer_name = ? AND product_name = ? AND quantity = ? AND total_price = ? AND payment_confirmed = 'Yes'"
        )) {
            psExist.setString(1, customerName);
            psExist.setString(2, productName);
            psExist.setString(3, quantityStr);
            psExist.setDouble(4, Double.parseDouble(totalPriceStr));
            ResultSet rsExist = psExist.executeQuery();
            rsExist.next();
            if (rsExist.getInt(1) > 0) {
                System.out.println("Skipping duplicate order at row " + (i + 1));
                skippedCount++;
                continue;
            }
        }

        // Check inventory
        String[] productNames = productName.split("\\s*,\\s*");
        String[] quantitiesArr = quantityStr.split("\\s*,\\s*");

        for (int j = 0; j < productNames.length; j++) {
            String prod = productNames[j];
            int qty = Integer.parseInt(quantitiesArr[j]);

            try (PreparedStatement psCheck = con.prepareStatement(
                    "SELECT quantity_available FROM food_inventory WHERE item_name = ?"
            )) {
                psCheck.setString(1, prod);
                ResultSet rsCheck = psCheck.executeQuery();
                if (rsCheck.next()) {
                    int available = rsCheck.getInt("quantity_available");
                    if (qty > available) {
                        JOptionPane.showMessageDialog(this, "Only " + available + " units available for " + prod + " in row " + (i + 1));
                        con.rollback();
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Product not found: " + prod + " in row " + (i + 1));
                    con.rollback();
                    return;
                }
            }
        }

        // Generate unique order ID
        String orderId;
        do {
            orderId = "ORD" + UUID.randomUUID().toString().replace("-", "").substring(0, 12).toUpperCase();
            try (PreparedStatement psCheckId = con.prepareStatement("SELECT COUNT(*) FROM customer_orders WHERE order_id = ?")) {
                psCheckId.setString(1, orderId);
                ResultSet rsCheckId = psCheckId.executeQuery();
                rsCheckId.next();
                if (rsCheckId.getInt(1) == 0)
                    break;
            }
        } while (true);

        Timestamp orderTime = new Timestamp(System.currentTimeMillis());

        pstInsert = con.prepareStatement(
                "INSERT INTO customer_orders (customer_name, product_name, quantity, unit_price, total_price, payment_method, payment_confirmed, order_status, order_time, order_id) " +
                        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
        );

        pstInsert.setString(1, customerName);
        pstInsert.setString(2, productName);
        pstInsert.setString(3, quantityStr);
        pstInsert.setString(4, unitPriceStr);
        pstInsert.setDouble(5, Double.parseDouble(totalPriceStr));
        pstInsert.setString(6, paymentMethod);
        pstInsert.setString(7, paymentConfirmed);
        pstInsert.setString(8, orderStatus);
        pstInsert.setTimestamp(9, orderTime);
        pstInsert.setString(10, orderId);
        pstInsert.executeUpdate();
        insertedCount++;
        
        for (int j = 0; j < productNames.length; j++) {
            String prod = productNames[j];
            int qty = Integer.parseInt(quantitiesArr[j]);

            try (PreparedStatement psUpdateInventory = con.prepareStatement(
                    "UPDATE food_inventory SET quantity_available = quantity_available - ? WHERE item_name = ?"
            )) {
                psUpdateInventory.setInt(1, qty);
                psUpdateInventory.setString(2, prod);
                psUpdateInventory.executeUpdate();
            }
        }
    
    }

    con.commit(); // All good
    JOptionPane.showMessageDialog(this, insertedCount + " orders inserted successfully.\n" +
            skippedCount + " duplicate/unconfirmed rows skipped.");

} catch (SQLException e) {
    try {
        if (con != null) con.rollback(); // Rollback on error
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error inserting orders: " + e.getMessage());
} finally {
    try {
        if (pstInsert != null) pstInsert.close();
        if (con != null) con.setAutoCommit(true); // Reset auto-commit
        if (con != null) con.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }

}







        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        model.removeRow(selectedRow);
        } else {
    JOptionPane.showMessageDialog(this, "Please select a row to delete.");
}    // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    try {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
    Statement stmt = con.createStatement();
    ResultSet rs = stmt.executeQuery("SELECT * FROM customer_orders");
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // clear existing
    
    while (rs.next()) {
        model.addRow(new Object[]{
            rs.getString("customer_name"),
            rs.getString("product_name"),
            rs.getString("quantity"),
            rs.getString("unit_price"),
            rs.getDouble("total_price"),
            rs.getString("payment_method"),
            rs.getString("payment_confirmed"),
            rs.getString("order_status"),
            rs.getTimestamp("order_time"),
            rs.getString("order_id")
        });
    }
    con.close();
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    
    
    private void updateQuantityComboBox(String productName) {
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
        String sql = "SELECT quantity_available FROM food_inventory WHERE item_name = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, productName);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            int availableQty = rs.getInt("quantity_available");

            // Populate jComboBox5 with new available values (1 to availableQty)
            jComboBox5.removeAllItems();
            for (int i = 1; i <= availableQty; i++) {
                jComboBox5.addItem(String.valueOf(i));
            }
        }

        rs.close();
        pst.close();
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error updating quantity combo: " + e.getMessage());
    }
}
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
int selectedRow = jTable1.getSelectedRow();

if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a row to delete.");
    return;
}

Object orderIdObj = jTable1.getValueAt(selectedRow, 9); // Change 9 if your order_id column index is different

if (orderIdObj == null) {
    JOptionPane.showMessageDialog(this, "Order ID is missing in the selected row.");
    return;
}

String orderId = orderIdObj.toString();

try {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
    
    // Step 1: Get the quantity ordered and the food item name (assuming there's a food_name or product_name column)
    String selectSql = "SELECT quantity, product_name FROM customer_orders WHERE order_id = ?";
    PreparedStatement selectPst = con.prepareStatement(selectSql);
    selectPst.setString(1, orderId);
    ResultSet rs = selectPst.executeQuery();
    
    if (rs.next()) {
        String quantityOrdered = rs.getString("quantity");  // <-- update column name here
        String productName = rs.getString("product_name");  // <-- update if your column name is different

        // Step 2: Update food_inventory to add back the quantity
        String updateSql = "UPDATE food_inventory SET quantity_available = quantity_available + ? WHERE item_name = ?";
        PreparedStatement updatePst = con.prepareStatement(updateSql);
        updatePst.setString(1, quantityOrdered);
        updatePst.setString(2, productName);

        int updateCount = updatePst.executeUpdate();

        if (updateCount > 0) {
            // Step 3: Delete the order from customer_orders
            String deleteSql = "DELETE FROM customer_orders WHERE order_id = ?";
            PreparedStatement deletePst = con.prepareStatement(deleteSql);
            deletePst.setString(1, orderId);
            int deleteCount = deletePst.executeUpdate();

            if (deleteCount > 0) {
                JOptionPane.showMessageDialog(this, "Order deleted and inventory updated successfully.");

                // Remove row from JTable
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.removeRow(selectedRow);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the order.");
            }
            deletePst.close();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update inventory.");
        }
        updatePst.close();
    } else {
        JOptionPane.showMessageDialog(this, "Order details not found.");
    }

    rs.close();
    selectPst.close();
    con.close();

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
}








            // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    
   
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
if (currentEditingOrderId == null) {
        JOptionPane.showMessageDialog(this, "No order selected for updating.");
        return;
    }

    try {
        // Read new values from form fields
        String newProduct = jComboBox4.getSelectedItem().toString();
        int newQty = Integer.parseInt(jComboBox5.getSelectedItem().toString());
        String newPayment = jComboBox1.getSelectedItem().toString();

        // Update database
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
        String updateQuery = "UPDATE orders SET product_name = ?, quantity = ?, payment_method = ? WHERE order_id = ?";
        PreparedStatement pst = con.prepareStatement(updateQuery);
        pst.setString(1, newProduct);
        pst.setInt(2, newQty);
        pst.setString(3, newPayment);
        pst.setString(4, currentEditingOrderId);

        int updated = pst.executeUpdate();
        con.close();

        if (updated > 0) {
            // Find the row in JTable that matches currentEditingOrderId and update it visually
            for (int row = 0; row < jTable1.getRowCount(); row++) {
                if (jTable1.getValueAt(row, 0).toString().equals(currentEditingOrderId)) {
                    jTable1.setValueAt(newProduct, row, 1);
                    jTable1.setValueAt(newQty, row, 2);
                    jTable1.setValueAt(newPayment, row, 3);
                    break;
                }
            }

            JOptionPane.showMessageDialog(this, "Order updated successfully.");

            // Reset editing state
            currentEditingOrderId = null;
            jButton8.setEnabled(false);

            // Optionally clear form fields
            jComboBox4.setSelectedIndex(-1);
            jComboBox5.setSelectedItem("");
            jComboBox1.setSelectedIndex(-1);
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update order.");
        }
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Quantity must be a number.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    
        
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    int selectedRow = jTable1.getSelectedRow();

if (selectedRow != -1) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    String paymentStatus = model.getValueAt(selectedRow, 6).toString().trim(); // Column 6 = payment_confirmation

    if (paymentStatus.equalsIgnoreCase("No")) {
        model.setValueAt("Yes", selectedRow, 6); // Change to "Yes"
        JOptionPane.showMessageDialog(this, "Payment confirmed for selected order.");
    } else {
        JOptionPane.showMessageDialog(this, "Payment is already confirmed.");
    }
} else {
    JOptionPane.showMessageDialog(this, "Please select a row to confirm payment.");
}




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    
    private int availableQty = 0;
    private boolean isComboBox5Ready = false;

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
    jComboBox5.removeAllItems(); // Clear quantity selections
    jComboBox6.removeAllItems(); // Clear unit price

    Object selected = jComboBox4.getSelectedItem();
    if (selected == null) return;

    String itemName = selected.toString();

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
        String query = "SELECT quantity_available, unit_price FROM food_inventory WHERE item_name = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, itemName);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            availableQty = rs.getInt("quantity_available");
            double unitPrice = rs.getDouble("unit_price");

            jComboBox6.addItem(String.valueOf(unitPrice));

            isComboBox5Ready = false;
            jComboBox5.removeAllItems();
            for (int i = 1; i <= 100; i++) {
                jComboBox5.addItem(String.valueOf(i));
            }
            isComboBox5Ready = true;
            

            // No jLabelQtyStatus.setText() since we're now using popups
        }

        rs.close();
        pst.close();
        con.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error loading item: " + ex.getMessage());
    }





//        String selected = jComboBox4.getSelectedItem().toString();
//        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
//             PreparedStatement pst = con.prepareStatement("SELECT unit_price, quantity FROM food_inventory WHERE item_name = ?")) {
//
//            pst.setString(1, selected);
//            ResultSet rs = pst.executeQuery();
//            if (rs.next()) {
//                jComboBox6.setSelectedItem(String.valueOf(rs.getInt("unit_price")));
//                jComboBox5.setSelectedItem("1"); // Default to 1
//                jTextField5.setText(String.valueOf(rs.getInt("unit_price"))); // Default total
//            }
//
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, ex.getMessage());
//        }
//  
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed


    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
    if (!isComboBox5Ready) return;
    // Get selected product from jComboBox4
    Object selectedProduct = jComboBox4.getSelectedItem();
    if (selectedProduct == null) return;

    String item_name = selectedProduct.toString();

    // Get selected quantity from jComboBox5
    Object selectedQty = jComboBox5.getSelectedItem();
    if (selectedQty == null) return;

    int customerQty = Integer.parseInt(selectedQty.toString());

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
        String query = "SELECT quantity_available FROM food_inventory WHERE item_name = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, item_name);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            int availableQty = rs.getInt("quantity_available");

            if (customerQty > availableQty) {
                JOptionPane.showMessageDialog(this, "Only " + availableQty + " portions available. Please reduce the quantity.");
                jComboBox5.setSelectedIndex(-1); // Reset selection
                return;
            }

            int remainingQty = availableQty - customerQty;

            // Show popup with remaining quantity
            JOptionPane.showMessageDialog(this, "After selecting " + customerQty + ", " + remainingQty + " portions will remain.");
        }

        rs.close();
        pst.close();
        con.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error checking remaining quantity: " + ex.getMessage());
    }

      // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
    jComboBox6.removeAllItems(); // Clear unit price items

    Object selected = jComboBox4.getSelectedItem();
    if (selected == null) return;

    String item_name = selected.toString();

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
        String query = "SELECT unit_price FROM food_inventory WHERE item_name = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, item_name);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            double unitPrice = rs.getDouble("unit_price");
            jComboBox6.addItem(String.valueOf(unitPrice));
        }

        rs.close();
        pst.close();
        con.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error loading unit price: " + ex.getMessage());
    }
   // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed



    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    try {
    String productName = jComboBox4.getSelectedItem().toString();
    int quantity = Integer.parseInt(jComboBox5.getSelectedItem().toString());
    double unitPrice = Double.parseDouble(jComboBox6.getSelectedItem().toString());

    if (quantity <= 0) {
        JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.");
        return;
    }

    // Check if already added and update quantity instead of duplicating
    boolean exists = false;
    for (OrderItem item : orderItems) {
        if (item.productName.equals(productName)) {
            item.quantity += quantity;
            exists = true;
            break;
        }
    }

    if (!exists) {
        orderItems.add(new OrderItem(productName, quantity, unitPrice));
    }

    int response = JOptionPane.showConfirmDialog(this, 
        "Item added to order.\nDo you want to add more items?", 
        "Add More?", 
        JOptionPane.YES_NO_OPTION);

    if (response == JOptionPane.YES_OPTION) {
        // User wants to add more items
        // Clear or reset the combo boxes for convenience
        jComboBox4.setSelectedIndex(0); // Reset product selection to first item
        jComboBox5.setSelectedIndex(0); // Reset quantity to first available (often 1)
        jComboBox6.setSelectedIndex(0); // Reset unit price accordingly
        // Optionally set focus to first combo box
        jComboBox4.requestFocusInWindow();
    } else {
        // User does NOT want to add more items
        // Close this window/dialog or proceed to next step
        // For example, if this is a dialog:
        
        // Or if you want to open a new form or do other logic here, add it
        // e.g., openOrderSummaryWindow();
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error adding item: " + e.getMessage());
}


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private String currentEditingOrderId = null;
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
   int selectedRow = jTable1.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select an order.");
    return;
}

String orderIdStr = (String) jTable1.getValueAt(selectedRow, 9); // get order_id as String

try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");
     PreparedStatement pst = con.prepareStatement("UPDATE customer_orders SET order_status = 'Not Served' WHERE order_id = ?")) {
    
    pst.setString(1, orderIdStr); // set as String since order_id is string type
    
    int updated = pst.executeUpdate();
    if (updated > 0) {
        JOptionPane.showMessageDialog(this, "Order sent to serving staff.");
        // refresh your table if needed
    } else {
        JOptionPane.showMessageDialog(this, "Failed to send order.");
    }
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    ArrayList<Order> previewOrders = new ArrayList<>();

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
String customerName = jTextField1.getText().trim(); // Text field for customer name

if (customerName.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter customer name before previewing.");
    return;
}

if (orderItems.isEmpty()) {
    JOptionPane.showMessageDialog(this, "No items have been added to the order.");
    return;
}

StringBuilder preview = new StringBuilder();
double grandTotal = 0.0;

preview.append("Order Preview for Customer: ").append(customerName).append("\n");
preview.append("------------------------------------------------------------\n");
preview.append(String.format("%-20s %-10s %-10s %-10s\n", "Product", "Qty", "Unit Price", "Total"));

for (OrderItem item : orderItems) {
    double total = item.getTotal();
    grandTotal += total;
    preview.append(String.format("%-20s %-10d %-10.2f %-10.2f\n",
        item.productName, item.quantity, item.unitPrice, total));
}

preview.append("------------------------------------------------------------\n");
preview.append(String.format("TOTAL AMOUNT: %.2f", grandTotal));

JOptionPane.showMessageDialog(this, preview.toString(), "Order Preview", JOptionPane.INFORMATION_MESSAGE);

  // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a transaction to print the receipt.");
            return;
        }

        // Check if payment is confirmed
        String paymentConfirmed = jTable1.getValueAt(selectedRow, getColumnIndex("payment_confirmed")).toString();
        if (!paymentConfirmed.equalsIgnoreCase("Yes")) {
            JOptionPane.showMessageDialog(null, "Payment must be confirmed before printing the receipt.");
            return;
        }

        // Collect receipt details
        String cafeteriaName = "My Cafeteria";
        String orderId = jTable1.getValueAt(selectedRow, getColumnIndex("order_id")).toString();
        String paymentMethod = jTable1.getValueAt(selectedRow, getColumnIndex("payment_method")).toString();
        String productName = jTable1.getValueAt(selectedRow, getColumnIndex("product_name")).toString();
        String quantity = jTable1.getValueAt(selectedRow, getColumnIndex("quantity")).toString();
        String unitPrice = jTable1.getValueAt(selectedRow, getColumnIndex("unit_price")).toString();
        String totalPrice = jTable1.getValueAt(selectedRow, getColumnIndex("total_price")).toString();
        String dateTime = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());

        // Format receipt
        StringBuilder receipt = new StringBuilder();
        receipt.append("======== " + cafeteriaName + " ========\n");
        receipt.append("Date/Time: " + dateTime + "\n");
        receipt.append("------------------------------\n");
        receipt.append("Item: " + productName + "\n");
        receipt.append("Quantity: " + quantity + "\n");
        receipt.append("Unit Price: ₦" + unitPrice + "\n");
        receipt.append("Total Price: ₦" + totalPrice + "\n");
        receipt.append("Payment Method: " + paymentMethod + "\n");
        receipt.append("------------------------------\n");
        receipt.append("Order ID: " + orderId + "\n");
        receipt.append("Thank you for your patronage!\n");
        receipt.append("======== RECEIPT END ========\n");

        // Send to printer
        printReceipt(receipt.toString());
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

     private int getColumnIndex(String columnName) {
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            if (jTable1.getColumnName(i).equalsIgnoreCase(columnName)) {
                return i;
            }
        }
        return -1;
    }
    public void loadTableData() {
    DefaultTableModel model = new DefaultTableModel();

    // Add column headers
    model.addColumn("Product Name");
    model.addColumn("Customer Name");
    model.addColumn("quantity");
    model.addColumn("unit price");
    model.addColumn("total price");
    model.addColumn("payment method");
    model.addColumn("payment confirmed");
    model.addColumn("Order Status");
    model.addColumn("Order Time"); // Add more columns as needed

    try {
        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006");

        String sql = "SELECT customer_name, product_name, quantity, unit_price, total_price, payment_method, payment_confirmed, order_status, order_time FROM customer_orders";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getString("customer_name"),
                rs.getString("product_name"),
                rs.getString("quantity"),
                rs.getString("unit_price"),
                rs.getString("total_price"),
                rs.getString("payment_method"),
                rs.getString("payment_confirmed"),
                rs.getString("order_status"),
                rs.getString("order_time")
            };
            model.addRow(row);
        }

        jTable1.setModel(model);

        rs.close();
        pst.close();
        con.close();

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading table: " + e.getMessage());
    }
}
    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
