/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unimanagement;


import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.Session;
import jakarta.mail.Transport;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Insets;
import java.awt.Window;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.util.Base64;
import java.sql.Timestamp;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;
import unimanagement.LoginSession;
import static unimanagement.registration.generateRandomPassword;

/**
 *
 * @author HP
 */
public class login extends javax.swing.JFrame {
    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
        String[] creds = LoginSession.loadCredentials();
        if (creds != null) {
            jTextField2.setText(creds[0]);
            jPasswordField1.setText(creds[1]);
            jCheckBox1.setSelected(true);
        }
        



    
    // ✅ G
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));

        jLabel11.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("RESET PASSWORD");

        jLabel12.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel12.setText("Username");

        jLabel13.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel13.setText("Email");

        jTextField3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 20)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Microsoft Himalaya", 1, 20)); // NOI18N

        jButton2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton2.setText("Reset Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField4))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(35, 35, 35))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\cafeteria\\src\\images\\pau_icon-150x150.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STAFF LOGIN SYSTEM");

        jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 1, 20)); // NOI18N
        jLabel6.setText("Password");

        jButton1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 20)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jCheckBox1.setText("Remember me");

        jLabel8.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("reset password");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel9.setText("Username");

        jTextField2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 20)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel5.setText("Don't have an account? Register");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jCheckBox1)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\cafeteria\\src\\images\\pau_icon-150x150.png")); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String username = jTextField2.getText().trim();
String password = new String(jPasswordField1.getPassword()).trim();

try {
    // ✅ Remember Me
    if (jCheckBox1.isSelected()) {
        LoginSession.saveCredentials(username, password);
    } else {
        LoginSession.clearCredentials();
    }

    String hashedPassword = HashingUtils.hashPassword(password);

    Connection conn = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/universitymanagement", "root", "Awele2006"
    );

    String sql = "SELECT * FROM registration WHERE name = ?";
    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, username);
    ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        String storedHash = rs.getString("password");
        String role = rs.getString("role").trim().toLowerCase();  // normalized role
        String unit = rs.getString("unit").trim().toLowerCase();
        String staffID = rs.getString("staffID");
        Timestamp expiry = rs.getTimestamp("password_expiry");

        if (storedHash.equals(hashedPassword)) {

            // ✅ Check if password expired
            if (expiry != null && expiry.before(new Timestamp(System.currentTimeMillis()))) {
                JOptionPane.showMessageDialog(null, "Your password has expired. Please reset it.");
                return;
            }

            // ✅ Save login session
            LoginSession.setLoggedInUser(username, role, unit, staffID);

            // ✅ Admin users
            if (role.equals("director of service") || role.equals("head of it department")) {
                JOptionPane.showMessageDialog(null, "Login successful as Admin Role: " + role);
                AdminDashboard dashboard = new AdminDashboard();
                dashboard.setVisible(true);

                Window loginWindow = SwingUtilities.getWindowAncestor(jTextField2);
                if (loginWindow != null) loginWindow.dispose();
                return;
            }

            // ✅ Strict Supervisor Role check
            if (role.equals("supervisor")) {
                JOptionPane.showMessageDialog(null, "Login successful as Supervisor of " + unit);
                new supervisordashboarddesign(unit).setVisible(true);

                Window loginWindow = SwingUtilities.getWindowAncestor(jTextField2);
                if (loginWindow != null) loginWindow.dispose();
                return;
            }

            // ✅ Non-supervisory Unit Staff
            JOptionPane.showMessageDialog(null, "Login successful as Unit: " + unit + ", Role: " + role);

            switch (unit) {
                case "cafeteria" -> new cafeteriaddesign().setVisible(true);
                case "facility" -> new facilitydesign().setVisible(true);
                case "horticulture" -> new horticulturedesign().setVisible(true);
                case "security" -> new securitydesign().setVisible(true);
                case "maintenance" -> new maintenancedesign().setVisible(true);
                default -> {
                    JOptionPane.showMessageDialog(null, "Unrecognized unit: " + unit);
                    return;
                }
            }

            // ✅ Close login window
            Window loginWindow = SwingUtilities.getWindowAncestor(jTextField2);
            if (loginWindow != null) loginWindow.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Incorrect username or password.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Incorrect username or password.");
    }

    conn.close();

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
    e.printStackTrace();
}









}

        // Password Hashing Function
        public class HashingUtils {

            public static String hashPassword(String password) throws NoSuchAlgorithmException {
                MessageDigest digest = MessageDigest.getInstance("SHA-256");
                byte[] encodedHash = digest.digest(password.getBytes(StandardCharsets.UTF_8));
                return Base64.getEncoder().encodeToString(encodedHash);
            }

            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        jDialog1.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabel8.setText("<html><a href='' style='color:#0056b3;'>Forgot Password?</a></html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jLabel8.setText("<html><a href=''>Reset Password?</a></html>"); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String username = jTextField3.getText().trim();
        String useremail = jTextField4.getText().trim();

        if (username.isEmpty() || useremail.isEmpty()) {
            JOptionPane.showMessageDialog(jDialog1, "Please fill both fields.");
            return;
        }

        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitymanagement", "root", "Awele2006")) {

            // Step 1: Check if user exists
            PreparedStatement checkUser = conn.prepareStatement("SELECT * FROM registration WHERE name=? AND email=?");
            checkUser.setString(1, username);
            checkUser.setString(2, useremail);
            ResultSet rs = checkUser.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(jDialog1, "Username and email do not match.");
                return;
            }

            // Step 2: Prompt for password generation or manual entry
            int choice = JOptionPane.showConfirmDialog(jDialog1, "Would you like the system to generate a new password?", "Password Choice", JOptionPane.YES_NO_OPTION);

            String newPassword;
            String resetMethod;

            if (choice == JOptionPane.YES_OPTION) {
                newPassword = generateRandomPassword();
                resetMethod = "generated";
            } else {
                // Show password input dialog with masking and show password checkbox
                JPasswordField passwordField = new JPasswordField(20);
                JCheckBox showPassword = new JCheckBox("Show Password");
                JPanel panel = new JPanel();
                panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
                panel.add(new JLabel("Enter new password:"));
                panel.add(passwordField);
                panel.add(showPassword);

                showPassword.addActionListener(e -> {
                    if (showPassword.isSelected()) {
                        passwordField.setEchoChar((char) 0);  // Show characters
                    } else {
                        passwordField.setEchoChar('*');        // Mask characters
                    }
                });

                int option = JOptionPane.showConfirmDialog(
                    jDialog1,
                    panel,
                    "Reset Password",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.PLAIN_MESSAGE);

                if (option != JOptionPane.OK_OPTION) {
                    JOptionPane.showMessageDialog(jDialog1, "Password reset cancelled.");
                    return;
                }

                newPassword = new String(passwordField.getPassword()).trim();

                if (newPassword.isEmpty()) {
                    JOptionPane.showMessageDialog(jDialog1, "Password cannot be empty.");
                    return;
                }

                // ✅ Password strength validation
                if (!validatePasswordStrength(newPassword)) {
                    JOptionPane.showMessageDialog(jDialog1,
                        "Password must be at least 8 characters long and include:\n" +
                        "- At least one uppercase letter\n" +
                        "- At least one lowercase letter\n" +
                        "- At least one digit\n" +
                        "- At least one special character (e.g., @#$%^&+=!)");
                    return;
                }

                resetMethod = "manual";
            }

            // Step 3: Hash the password
            String hashedNewPassword = HashingUtils.hashPassword(newPassword);

            // Step 4: Check password reuse
            PreparedStatement historyCheck = conn.prepareStatement("SELECT * FROM password_history WHERE email=? AND password_hash=?");
            historyCheck.setString(1, useremail);
            historyCheck.setString(2, hashedNewPassword);
            ResultSet historyRs = historyCheck.executeQuery();
            if (historyRs.next()) {
                JOptionPane.showMessageDialog(jDialog1, "You cannot reuse a previously used password.");
                return;
            }

            // Step 5: Update password in registration table
            PreparedStatement update = conn.prepareStatement("UPDATE registration SET password=? WHERE email=?");
            update.setString(1, hashedNewPassword);
            update.setString(2, useremail);
            update.executeUpdate();

            // ---- UPDATE password_expiry to 90 days from now ----
            PreparedStatement updateExpiry = conn.prepareStatement("UPDATE registration SET password_expiry = ? WHERE email = ?");
            long millisIn90Days = 90L * 24 * 60 * 60 * 1000; // 90 days in milliseconds
            java.sql.Timestamp expiryTimestamp = new java.sql.Timestamp(System.currentTimeMillis() + millisIn90Days);
            updateExpiry.setTimestamp(1, expiryTimestamp);
            updateExpiry.setString(2, useremail);
            updateExpiry.executeUpdate();

            // Step 6: Log to password_history table
            PreparedStatement logHistory = conn.prepareStatement("INSERT INTO password_history(email, password_hash) VALUES(?, ?)");
            logHistory.setString(1, useremail);
            logHistory.setString(2, hashedNewPassword);
            logHistory.executeUpdate();

            // Step 7: Log to passwordresetlog table
            PreparedStatement logReset = conn.prepareStatement("INSERT INTO passwordresetlog(username, email, reset_time) VALUES(?, ?, ?)");
            logReset.setString(1, username);
            logReset.setString(2, useremail);
            logReset.setTimestamp(3, new Timestamp(System.currentTimeMillis()));
            logReset.executeUpdate();

            // Step 8: Send email
            String subject = "Your Password Has Been Reset";
            String body = "Hi " + username + ",\n\nYour new password is: " + newPassword +
            "\n\nPlease keep it from unathorized users.\n\nRegards,\nAdmin Team";

            email.sendEmail(useremail, subject, body);
            JOptionPane.showMessageDialog(jDialog1, "Password reset successfully. Check your email.");
            jDialog1.dispose();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(jDialog1, "Error: " + ex.getMessage());
        }

        //    String username = jTextField3.getText().trim();
        //    String useremail = jTextField4.getText().trim();
        //
        //    if (username.isEmpty() || useremail.isEmpty()) {
            //        JOptionPane.showMessageDialog(jDialog1, "Please fill both fields.");
            //        return;
            //    }
        //
        //    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteria", "root", "Awele2006")) {
            //        // Check if user exists with matching email
            //        String sql = "SELECT * FROM registration WHERE name = ? AND email = ?";
            //        PreparedStatement pst = conn.prepareStatement(sql);
            //        pst.setString(1, username);
            //        pst.setString(2, useremail);
            //        ResultSet rs = pst.executeQuery();
            //
            //        if (!rs.next()) {
                //            JOptionPane.showMessageDialog(jDialog1, "Username and email do not match.");
                //            return;
                //        }
            //
            //        // Show password input dialog with masking and show password checkbox
            //        JPasswordField passwordField = new JPasswordField(20);
            //        JCheckBox showPassword = new JCheckBox("Show Password");
            //        JPanel panel = new JPanel();
            //        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
            //        panel.add(new JLabel("Enter new password:"));
            //        panel.add(passwordField);
            //        panel.add(showPassword);
            //
            //        showPassword.addActionListener(e -> {
                //            if (showPassword.isSelected()) {
                    //                passwordField.setEchoChar((char) 0);  // Show characters
                    //            } else {
                    //                passwordField.setEchoChar('*');        // Mask characters
                    //            }
                //        });
        //
        //        int option = JOptionPane.showConfirmDialog(
            //                jDialog1,
            //                panel,
            //                "Reset Password",
            //                JOptionPane.OK_CANCEL_OPTION,
            //                JOptionPane.PLAIN_MESSAGE);
        //
        //        if (option != JOptionPane.OK_OPTION) {
            //            JOptionPane.showMessageDialog(jDialog1, "Password reset cancelled.");
            //            return;
            //        }
        //
        //        String newPassword = new String(passwordField.getPassword());
        //
        //        if (newPassword.isEmpty()) {
            //            JOptionPane.showMessageDialog(jDialog1, "Password cannot be empty.");
            //            return;
            //        }
        //
        //        // Password strength validation: minimum 8 chars, at least one uppercase, lowercase, digit, special char
        //        if (!newPassword.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=!]).{8,}$")) {
            //            JOptionPane.showMessageDialog(jDialog1,
                //                    "Password must be at least 8 characters and include uppercase, lowercase, number, and symbol.");
            //            return;
            //        }
        //
        //        // Hash the new password with SHA-256
        //        String hashedPassword;
        //        try {
            //            MessageDigest md = MessageDigest.getInstance("SHA-256");
            //            byte[] hash = md.digest(newPassword.getBytes(StandardCharsets.UTF_8));
            //            hashedPassword = Base64.getEncoder().encodeToString(hash);
            //        } catch (NoSuchAlgorithmException ex) {
            //            ex.printStackTrace();
            //            JOptionPane.showMessageDialog(jDialog1, "Error hashing password.");
            //            return;
            //        }
        //
        //        // Update password in the registration table
        //        String updateSql = "UPDATE registration SET password = ? WHERE name = ? AND email = ?";
        //        PreparedStatement updatePst = conn.prepareStatement(updateSql);
        //        updatePst.setString(1, hashedPassword);
        //        updatePst.setString(2, username);
        //        updatePst.setString(3, useremail);
        //
        //        int updatedRows = updatePst.executeUpdate();
        //        if (updatedRows == 0) {
            //            JOptionPane.showMessageDialog(jDialog1, "Failed to update password.");
            //            return;
            //        }
        //
        //       // Log the password reset event (optional, if you have a passwordresetlog table)
        //
        //        String logSql = "INSERT INTO passwordresetlog (username, email, reset_time) VALUES (?, ?, NOW())";
        //        PreparedStatement logPst = conn.prepareStatement(logSql);
        //        logPst.setString(1, username);
        //        logPst.setString(2, useremail);
        //        logPst.executeUpdate();
        //
        //
        //        // Send email with the new password
        //        try {
            //            String subject = "Your New Password";
            //            String body = "Hello " + username + ",\n\nYour password has been reset.\nYour new password is: "
            //                    + newPassword + "\n\nEnsure to keep the password safe.\n\nRegards,\nAdmin Team";
            //
            //            email.sendEmail(useremail, subject, body);  // Use your existing email sending method
            //            JOptionPane.showMessageDialog(jDialog1, "New password sent to email.");
            //            jDialog1.dispose();
            //
            //        } catch (Exception ex) {
            //            ex.printStackTrace();
            //            JOptionPane.showMessageDialog(jDialog1, "Failed to send email.");
            //        }
        //
        //    } catch (Exception ex) {
        //        ex.printStackTrace();
        //        JOptionPane.showMessageDialog(jDialog1, "Database error: " + ex.getMessage());
        //    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    new registration().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
    jLabel5.setText("<html>Don't have an account? <a href=''>Register</a></html>");
    jLabel5.setCursor(new Cursor(Cursor.HAND_CURSOR));    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    
       private boolean validatePasswordStrength(String password) {
    if (password.length() < 8) return false;
    if (!password.matches(".*[A-Z].*")) return false;        // At least one uppercase
    if (!password.matches(".*[a-z].*")) return false;        // At least one lowercase
    if (!password.matches(".*\\d.*")) return false;          // At least one digit
    if (!password.matches(".*[@#$%^&+=!].*")) return false;  // At least one special char
    return true;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//           AdminDashboard dashboard = new AdminDashboard();
//        dashboard.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
