/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unimanagement;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import com.github.sarxos.webcam.Webcam;
import java.sql.Connection;
import jakarta.mail.Authenticator;
import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.PasswordAuthentication;
import jakarta.mail.Session;
import jakarta.mail.Transport;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.BorderLayout;
import java.awt.Graphics2D;
import java.io.ByteArrayOutputStream;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Date;
import java.util.Properties;
import javax.swing.Icon;
import javax.swing.SwingConstants;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Random;
import java.sql.SQLException;
import java.util.Base64;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import com.digitalpersona.onetouch.*;
import com.digitalpersona.onetouch.capture.*;
import com.digitalpersona.onetouch.capture.event.*;
import com.digitalpersona.onetouch.processing.*;
import com.digitalpersona.onetouch.verification.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

import com.digitalpersona.onetouch.DPFPDataPurpose;
import com.digitalpersona.onetouch.DPFPFeatureSet;
import com.digitalpersona.onetouch.DPFPGlobal;
import com.digitalpersona.onetouch.DPFPSample;
import com.digitalpersona.onetouch.DPFPTemplate;
import com.digitalpersona.onetouch.capture.DPFPCapture;
import com.digitalpersona.onetouch.capture.event.DPFPDataAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPDataEvent;
import com.digitalpersona.onetouch.capture.event.DPFPErrorAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPErrorEvent;
import com.digitalpersona.onetouch.capture.event.DPFPReaderStatusAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPReaderStatusEvent;
import com.digitalpersona.onetouch.capture.event.DPFPSensorAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPSensorEvent;
import com.digitalpersona.onetouch.processing.DPFPEnrollment;
import com.digitalpersona.onetouch.processing.DPFPFeatureExtraction;
import com.digitalpersona.onetouch.processing.DPFPImageQualityException;
import com.digitalpersona.onetouch.processing.DPFPTemplateStatus;
import com.digitalpersona.onetouch.verification.DPFPVerification;
import java.io.ByteArrayInputStream;





/**
 *
 * @author HP
 */
public class registration extends javax.swing.JFrame {
    private DPFPCapture fingerprintReader = DPFPGlobal.getCaptureFactory().createCapture();
    private DPFPEnrollment enrollmentHandler = DPFPGlobal.getEnrollmentFactory().createEnrollment();
    private DPFPTemplate fingerTemplate = null;


//    private DPFPCapture capturer;
//private DPFPTemplate fingerprintTemplate;
//private byte[] fingerprintData;
//
//    
//
//    /**
//     * Creates new form registration
//     */
    public registration() {
        initComponents();
        startFingerprintCapture();
        setupFingerprintListeners();

//        capturer = DPFPCaptureFactory.createCapture();
//
//capturer.addDataListener(new DPFPDataAdapter() {
//    @Override
//    public void dataAcquired(DPFPSampleEvent e) {
//        DPFPSample sample = e.getSample();
//        processSample(sample);
//    }
//});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAU STAFF MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STAFF REGISTRATION FORM");

        jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel4.setText("Date of Birth");

        jLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel5.setText("Phone number");

        jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel7.setText("Gender");

        jLabel8.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel8.setText("Unit");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Microsoft Himalaya", 3, 22)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "other", "Prefer not to say" }));

        jComboBox2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Role", "Supervisor", "Non-Supervisor", "Director of Service", "Head of IT Department" }));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("No Photo");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel9.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel10.setText("Passport photograph");

        jButton1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton1.setText("Upload Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jButton2.setText("Webcam");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jButton3.setText("Register");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel12.setText("Role");

        jComboBox3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Unit", "Security", "Horticulture", "Facility", "Cafeteria", "Maintenance", "Director of Service", "Head of IT Department" }));

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel14.setText("Fingerprint capture");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(46, 46, 46)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jComboBox1, 0, 245, Short.MAX_VALUE)
                                                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(46, 46, 46)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextField3)
                                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(77, 77, 77)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\unimanagement\\src\\images\\pau_icon-150x150.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Passport Photograph");
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
            "Image files", "jpg", "jpeg", "png"));

    int result = fileChooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        java.io.File imageFile = fileChooser.getSelectedFile();

        try {
            BufferedImage image = ImageIO.read(imageFile);

            // Resize image to fit the label size
            Image scaledImage = image.getScaledInstance(
                jLabel9.getWidth(),
                jLabel9.getHeight(),
                Image.SCALE_SMOOTH
            );

            jLabel9.setIcon(new ImageIcon(scaledImage));
            jLabel9.setText(""); // Remove "No Photo" text

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed to load image: " + e.getMessage());
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private Webcam webcam;
    private boolean streaming = false;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (webcam != null && webcam.isOpen()) {
            return; // Already open
        }

        try {
            webcam = Webcam.getDefault();
            if (webcam == null) {
                JOptionPane.showMessageDialog(this, "No webcam detected.");
                return;
            }

            webcam.setViewSize(new java.awt.Dimension(320, 240));
            webcam.open();

            // Create a temporary JFrame to show the webcam live preview
            JFrame previewFrame = new JFrame("Position Your Face - Webcam Preview");
            previewFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            previewFrame.setSize(360, 340);
            previewFrame.setLayout(new BorderLayout());
            previewFrame.setLocationRelativeTo(this);

            JLabel previewLabel = new JLabel();
            previewLabel.setHorizontalAlignment(SwingConstants.CENTER);
            previewFrame.add(previewLabel, BorderLayout.CENTER);

            JButton captureButton = new JButton("Capture");
            previewFrame.add(captureButton, BorderLayout.SOUTH);
            previewFrame.setVisible(true);

            // Thread to continuously update the webcam preview
            Thread previewThread = new Thread(() -> {
                while (previewFrame.isVisible() && webcam.isOpen()) {
                    BufferedImage image = webcam.getImage();
                    if (image != null) {
                        Image scaled = image.getScaledInstance(
                            previewLabel.getWidth(),
                            previewLabel.getHeight(),
                            Image.SCALE_SMOOTH
                        );
                        previewLabel.setIcon(new ImageIcon(scaled));
                    }
                    try {
                        Thread.sleep(100); // Refresh every 100ms
                    } catch (InterruptedException e) {
                        break;
                    }
                }
            });
            previewThread.setDaemon(true);
            previewThread.start();

            // When user clicks Capture
            captureButton.addActionListener(e -> {
                if (webcam != null && webcam.isOpen()) {
                    BufferedImage capturedImage = webcam.getImage();
                    if (capturedImage != null) {
                        Image scaled = capturedImage.getScaledInstance(
                            jLabel9.getWidth(),
                            jLabel9.getHeight(),
                            Image.SCALE_SMOOTH
                        );
                        jLabel9.setIcon(new ImageIcon(scaled));
                        jLabel9.setText(""); // Remove "No Photo"
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to capture image.");
                    }
                }

                previewFrame.dispose();
                if (webcam != null) {
                    webcam.close();
                    webcam = null;
                }
            });

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Webcam error: " + e.getMessage());
            if (webcam != null) {
                webcam.close();
                webcam = null;
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public class HashingUtils {

    public static String hashPassword(String password) throws NoSuchAlgorithmException {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        byte[] encodedHash = digest.digest(password.getBytes(StandardCharsets.UTF_8));
        return Base64.getEncoder().encodeToString(encodedHash);
    }
}
  
    
     private String generateStaffID(String unit) {
        String prefix = switch (unit.toLowerCase()) {
        case "cafeteria" -> "CAF";
        case "security" -> "SEC";
        case "maintenance" -> "MAI";
        case "facility" -> "FAC";
        case "horticulture" -> "HOR";
        default -> "GEN";
    };

 String staffID;
    try (Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/universitymanagement", "root", "Awele2006")) {

        PreparedStatement ps = conn.prepareStatement(
            "SELECT COUNT(*) FROM registration WHERE staffID = ?");

        do {
            // Generate a random 12-character alphanumeric string
            String randomPart = UUID.randomUUID().toString().replace("-", "")
                    .substring(0, 5).toUpperCase();
            staffID = prefix + randomPart;

            ps.setString(1, staffID);
            ResultSet rs = ps.executeQuery();
            rs.next();
            if (rs.getInt(1) == 0) break; // Unique ID found, exit loop
        } while (true);

    } catch (Exception e) {
        e.printStackTrace();
        staffID = null;
    }

    return staffID;

    }
    // Generate a random password (8 characters long)
public static String generateRandomPassword() {
    StringBuilder password = new StringBuilder();
    String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()";
    Random random = new Random();
    for (int i = 0; i < 8; i++) {  // 8 character password
        int index = random.nextInt(chars.length());
        password.append(chars.charAt(index));
    }
    return password.toString();
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// Validate Inputs
String name = jTextField1.getText();
if (name.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please enter a full name!");
    return;
}

Date dob = jDateChooser1.getDate();
if (dob == null) {
    JOptionPane.showMessageDialog(null, "Please enter a date of birth!");
    return;
}

String phone = jTextField3.getText();
if (phone.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please enter a phone number!");
    return;
}

String email = jTextField4.getText();
if (email.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please enter an email!");
    return;
}

String unit = jComboBox3.getSelectedItem().toString();
if (jComboBox3.getSelectedIndex() <= 0) {
    JOptionPane.showMessageDialog(null, "Please select a unit!");
    return;
}

String role = jComboBox2.getSelectedItem().toString();
if (jComboBox2.getSelectedIndex() <= 0) {
    JOptionPane.showMessageDialog(null, "Please select a role!");
    return;
}

String gender = jComboBox1.getSelectedItem().toString();
if (!gender.equals("Male") && !gender.equals("Female")) {
    JOptionPane.showMessageDialog(null, "Invalid gender selected.");
    return;
}

// Validate fingerprint
if (fingerTemplate == null) {
    JOptionPane.showMessageDialog(
        rootPane,
        "Please capture fingerprint before registering.",
        "Fingerprint Missing",
        JOptionPane.ERROR_MESSAGE
    );
    return;
}

byte[] fingerprint = fingerTemplate.serialize(); // Serialized fingerprint byte array

// Generate and hash the password
String password = generateRandomPassword();
String hashedPassword = null;
try {
    hashedPassword = HashingUtils.hashPassword(password);
} catch (NoSuchAlgorithmException e) {
    JOptionPane.showMessageDialog(this, "Error while hashing password: " + e.getMessage());
    return;
}

// Extract photo from jLabel9
byte[] photo = null;
try {
    Icon icon = jLabel9.getIcon();
    if (icon instanceof ImageIcon) {
        Image image = ((ImageIcon) icon).getImage();
        BufferedImage bufferedImage = new BufferedImage(
            image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = bufferedImage.createGraphics();
        g2d.drawImage(image, 0, 0, null);
        g2d.dispose();

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        ImageIO.write(bufferedImage, "jpg", baos);
        photo = baos.toByteArray();
    }
} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error processing photo: " + ex.getMessage());
    return;
}

// Prepare SQL Date
java.sql.Date sqlDob = new java.sql.Date(dob.getTime());
String staffID = generateStaffID(unit);

// Insert into database
try (Connection con = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/universitymanagement", "root", "Awele2006")) {

    String query = "INSERT INTO registration (staffID, name, dob, phone, email, gender, unit, role, passportphoto, password, fingerprint) "
                 + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    try (PreparedStatement ps = con.prepareStatement(query)) {
        ps.setString(1, staffID);
        ps.setString(2, name);
        ps.setDate(3, sqlDob);
        ps.setString(4, phone);
        ps.setString(5, email);
        ps.setString(6, gender);
        ps.setString(7, unit);
        ps.setString(8, role);
        ps.setBytes(9, photo);
        ps.setString(10, hashedPassword); // Set fingerprint byte array
        ps.setBytes(11, fingerprint);

        int rowsAffected = ps.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Registration successful!\nStaff ID: " + staffID);
            sendConfirmationEmail(email, name, password); // Email with raw password
        } else {
            JOptionPane.showMessageDialog(this, "Registration failed.");
        }
    }
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
}

        }

        // Helper method for sending email
        private void sendConfirmationEmail(String email, String username, String password) {
            String from = "udsako@gmail.com";
            String senderPassword = "rzvqeubeobzljlkl"; // Better to store this securely

            Properties props = new Properties();
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.starttls.enable", "true");
            props.put("mail.smtp.host", "smtp.gmail.com");
            props.put("mail.smtp.port", "587");

            Session session = Session.getInstance(props, new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(from, senderPassword);
                }
            });

            try {
                String body = "Hello, Registration Complete.\n\n" +
                "Your Username: " + username + "\n" +
                "Your Password: " + password + "\n\n" +
                "Remember your passcode.";

                Message message = new MimeMessage(session);
                message.setFrom(new InternetAddress(from));
                message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(email));
                message.setSubject("Registration Completed");
                message.setText(body);

                Transport.send(message);
                JOptionPane.showMessageDialog(this, "Email sent to user.");
            } catch (MessagingException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Failed to send email.");
            }
    }//GEN-LAST:event_jButton3ActionPerformed

        
        
        private void startFingerprintCapture() {
        fingerprintReader.startCapture();
        jLabel15.setText("Scanner: Connected");
        // jLabel36.setText("Scanner: Connected"); // status label under “Fingerprint”
    }

    private void stopFingerprintCapture() {
        fingerprintReader.stopCapture();
        jLabel15.setText("Scanner: Idle");
        // jLabel36.setText("Scanner: Idle");

    }

    private void setupFingerprintListeners() {
        // 4.2.a When the device reads data
        fingerprintReader.addDataListener(new DPFPDataAdapter() {
            @Override
            public void dataAcquired(final DPFPDataEvent e) {
                // Called when a fingerprint sample is captured
                SwingUtilities.invokeLater(() -> {
                    // Show a status message
                    jLabel13.setText("Capturing fingerprint…");
//                    jLabel36.setText("Capturing fingerprint…");
                    // Send sample to processing
                    FingerCaptureProcess(e.getSample());
                });
            }
        });

        // 4.2.b Reader connected / disconnected
        fingerprintReader.addReaderStatusListener(new DPFPReaderStatusAdapter() {
            @Override
            public void readerConnected(final DPFPReaderStatusEvent e) {
                SwingUtilities.invokeLater(() -> jLabel13.setText("Scanner: Connected"));
//                SwingUtilities.invokeLater(() -> jLabel36.setText("Scanner: Connected"));

            }

            @Override
            public void readerDisconnected(final DPFPReaderStatusEvent e) {
                SwingUtilities.invokeLater(() -> jLabel13.setText("Scanner: Disconnected"));
//                SwingUtilities.invokeLater(() -> jLabel36.setText("Scanner: Disconnected"));

            }
        });

        // 4.2.c Finger touched / removed
        fingerprintReader.addSensorListener(new DPFPSensorAdapter() {
            @Override
            public void fingerTouched(final DPFPSensorEvent e) {
                SwingUtilities.invokeLater(() -> jLabel13.setText("Place finger on scanner"));
//                SwingUtilities.invokeLater(() -> jLabel36.setText("Place finger on scanner"));

            }

            public void fingerRemoved(final DPFPSensorEvent e) {
                SwingUtilities.invokeLater(() -> jLabel13.setText("Finger removed"));
//                SwingUtilities.invokeLater(() -> jLabel36.setText("Finger removed"));

            }
        });

        // 4.2.d Error handling
        fingerprintReader.addErrorListener(new DPFPErrorAdapter() {
            public void errorReader(final DPFPErrorEvent e) {
                SwingUtilities.invokeLater(()
                        -> jLabel13.setText("Error: " + e.getError())
                );
//                SwingUtilities.invokeLater(()
//                        -> jLabel36.setText("Error: " + e.getError())
//                );
            }
        });
    }

// ────────────────────────────
// 4.3 Extract Features from Sample
// ────────────────────────────
    private DPFPFeatureSet extractFingerPrintCharacteristic(
            DPFPSample sample, DPFPDataPurpose purpose) {
        DPFPFeatureExtraction extractor
                = DPFPGlobal.getFeatureExtractionFactory().createFeatureExtraction();
        try {
            return extractor.createFeatureSet(sample, purpose);
        } catch (DPFPImageQualityException e) {
            return null;
        }
    }

// ────────────────────────────
// 4.4 Process a Captured Sample
// ────────────────────────────
    private void FingerCaptureProcess(DPFPSample sample) {
        // 1) Extract features for enrollment
        DPFPFeatureSet features
                = extractFingerPrintCharacteristic(sample, DPFPDataPurpose.DATA_PURPOSE_ENROLLMENT);

        if (features != null) {
            try {
                // 2) Add features to enrollment handler
                enrollmentHandler.addFeatures(features);

                // 3) Convert sample → image and display
                Image img = createFingerprintImage(sample);
                displayFingerprintImage(img);
                displayFingerprintImage1(img);

//                jLabel22.setText("Fingerprint captured. Remove finger.");
//                jLabel36.setText("Fingerprint captured. Remove finger.");
            } catch (DPFPImageQualityException ex) {
                return; // image quality was insufficient
            } finally {
                // 4) Check if we have a valid template
                switch (enrollmentHandler.getTemplateStatus()) {
                    case DPFPTemplateStatus.TEMPLATE_STATUS_READY:
                        fingerTemplate = enrollmentHandler.getTemplate();
                        stopFingerprintCapture();
//                        jLabel22.setText("Fingerprint ready for DB.");
//                        jLabel36.setText("Fingerprint ready for DB.");

                        JOptionPane.showMessageDialog(
                                this,
                                "Fingerprint captured successfully!",
                                "Fingerprint",
                                JOptionPane.INFORMATION_MESSAGE
                        );
                        break;

                    case DPFPTemplateStatus.TEMPLATE_STATUS_FAILED:
                        enrollmentHandler.clear();
                        stopFingerprintCapture();
//                        jLabel22.setText("Capture failed. Try again.");
//                        jLabel36.setText("Capture failed. Try again.");
                        startFingerprintCapture();
                        break;
                }

            }
        }
    }

// ─────────────────────────────────────────
// 4.5 Create an Image from the Sample
// ─────────────────────────────────────────
    private Image createFingerprintImage(DPFPSample sample) {
        return DPFPGlobal.getSampleConversionFactory()
                .createImage(sample);
    }

// ─────────────────────────────────────────
// 4.6 Display the Fingerprint Image in jLabel20
// ─────────────────────────────────────────
    private void displayFingerprintImage(Image img) {
        // Scale to fit jLabel20’s size
        img = img.getScaledInstance(
                jLabel13.getWidth(),
                jLabel13.getHeight(),
                Image.SCALE_DEFAULT
        );
        jLabel13.setIcon(new ImageIcon(img));
        repaint();
    }

    private void displayFingerprintImage1(Image img) {
        // Scale to fit jLabel20’s size
//        img = img.getScaledInstance(
        ////                jLabel34.getWidth(),
////                jLabel34.getHeight(),
//                Image.SCALE_DEFAULT
//        );
        //jLabel34.setIcon(new ImageIcon(img));
        repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
