/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unimanagement;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class supervisordashboarddesign extends javax.swing.JFrame {
    private String unit;
    private JLabel backgroundLabel;

    public supervisordashboarddesign(String unit) {
        this.unit = unit;
        initComponents(); // Initializes jLabel1 (created from NetBeans GUI)

        // Make JFrame full screen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        try {
            // Load image from resources
            InputStream imageStream = getClass().getResourceAsStream("/images/pau_background.jpg");
            if (imageStream == null) {
                throw new IOException("Image not found in /images/pau_background.jpg");
            }

            BufferedImage original = ImageIO.read(imageStream);
            BufferedImage blurred = blurImage(original);

            // Get screen size
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

            // Scale blurred image to screen size
            Image scaledImage = blurred.getScaledInstance(screenSize.width, screenSize.height, Image.SCALE_SMOOTH);

            // Set as background
            backgroundLabel = new JLabel(new ImageIcon(scaledImage));
            backgroundLabel.setLayout(null); // Allow absolute positioning of components
            setContentPane(backgroundLabel);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error loading background image: " + e.getMessage());
            e.printStackTrace();
        }


        JLabel welcomeLabel = new JLabel("WELCOME SUPERVISOR");
        welcomeLabel.setFont(new Font("Segoe UI", Font.BOLD, 36));
        welcomeLabel.setForeground(Color.BLUE); // You can also try Color.WHITE or Color.YELLOW
        welcomeLabel.setBounds(455, 290, 800, 50);
        backgroundLabel.add(welcomeLabel);


        JButton dashboardBtn = new JButton("Supervisor Dashboard");
        dashboardBtn.setFont(new Font("Segoe UI", Font.BOLD, 18));
        dashboardBtn.setBounds(532, 350, 270, 45);
        backgroundLabel.add(dashboardBtn);

        dashboardBtn.addActionListener(e -> new supervisordashboard("Cafeteria").setVisible(true));
    }

    // Blurring method
    private BufferedImage blurImage(BufferedImage image) {
        float[] matrix = {
            1f/9f, 1f/9f, 1f/9f,
            1f/9f, 1f/9f, 1f/9f,
            1f/9f, 1f/9f, 1f/9f
        };
        BufferedImageOp op = new ConvolveOp(new Kernel(3, 3, matrix));
        return op.filter(image, null);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supervisordashboarddesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supervisordashboarddesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supervisordashboarddesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supervisordashboarddesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String unit = null;
                new supervisordashboarddesign(unit).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
