/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unimanagement;

import java.awt.*;
import java.awt.event.*;
import java.awt.image.*;
import java.io.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
/**
 *
 * @author HP
 */
public class welcome extends javax.swing.JFrame {
     private JLabel backgroundLabel;

    public welcome() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        try {
            // Load background image from resource folder
            InputStream imageStream = getClass().getResourceAsStream("/images/pau_background.jpg");
            if (imageStream == null) {
                throw new IOException("Image not found: /images/pau_background.jpg");
            }

            BufferedImage original = ImageIO.read(imageStream);
            BufferedImage blurred = blurImage(original);

            // Resize image to screen resolution
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            Image scaledImage = blurred.getScaledInstance(screenSize.width, screenSize.height, Image.SCALE_SMOOTH);

            backgroundLabel = new JLabel(new ImageIcon(scaledImage));
            backgroundLabel.setLayout(null); // Use absolute layout
            setContentPane(backgroundLabel);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Failed to load background image: " + e.getMessage());
            e.printStackTrace();
        }

        // ========= Add Centered Welcome Message =========
        JLabel title = new JLabel("WELCOME TO PAU STAFF ATTENDANCE MANAGEMENT SYSTEM (PSAMS)", SwingConstants.CENTER);
        title.setFont(new Font("Segoe UI", Font.BOLD, 28));
        title.setForeground(Color.BLUE);
        title.setBounds(150, 290, 1000, 100); // Adjust width as needed
        backgroundLabel.add(title);

        // ========= Add Login Button Centered =========
        JButton loginButton = new JButton("Login");
        loginButton.setFont(new Font("Segoe UI", Font.BOLD, 20));
        loginButton.setBounds(550, 400, 200, 45);
        backgroundLabel.add(loginButton);

        // 🎯 Action: Open Login Frame (you can replace this)
        loginButton.addActionListener(e -> {
            new login().setVisible(true); // Replace 'loginPage' with your login JFrame
            dispose();
        });
    }

    private BufferedImage blurImage(BufferedImage image) {
        float[] matrix = {
            1f/9f, 1f/9f, 1f/9f,
            1f/9f, 1f/9f, 1f/9f,
            1f/9f, 1f/9f, 1f/9f
        };
        BufferedImageOp op = new ConvolveOp(new Kernel(3, 3, matrix));
        return op.filter(image, null);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
